### ISSUE TITLE
验证码显示不出来

### ISSUE THREAD

**Issue by cool2008** [ExcaliburEX/AutomaticOnlineAnswer#1]
![2](https://user-images.githubusercontent.com/66152697/83318956-6ac9d000-a26c-11ea-859e-1b5762ed2162.PNG)

**Comment by ExcaliburEX** [comment]
应该是网络卡顿，长时间显示不出来后，先点登录，再获取验证码一次。

**Comment by ExcaliburEX** [comment]
> 应该是网络卡顿，长时间显示不出来后，先点登录，再获取验证码一次。

看看是否解决问题
