### ISSUE TITLE
周周练出错

### ISSUE THREAD

**Issue by cool2008** [ExcaliburEX/AutomaticOnlineAnswer#2]
![Uploading 1.PNG…]()
![2](https://user-images.githubusercontent.com/66152697/83371709-d3908400-a3f5-11ea-9471-adae1c21d705.PNG)

**Comment by cool2008** [comment]
![1](https://user-images.githubusercontent.com/66152697/83371737-e86d1780-a3f5-11ea-90a1-23f7a0a6e2af.PNG)

**Comment by ExcaliburEX** [comment]
由于chrome更新或者driver更新问题。
1. 首先下载最新的release，3.1版本，我已上传，如已解决问题不需要第二步；
2. 根据自己目前的chrome版本更新一下driver版本。
