### ISSUE TITLE
月月比什么时候能推出？期待大神更新哈~~

### ISSUE THREAD

**Issue by cool2008** [ExcaliburEX/AutomaticOnlineAnswer#3]
题库偶有找不到的题目，刷新验证码和更新做题数据比较慢，其他完美。

**Comment by ExcaliburEX** [comment]
> 题库偶有找不到的题目，刷新验证码和更新做题数据比较慢，其他完美。

刷新验证码因为是要打开浏览器，所以跟电脑性能有关。

更新数据也是，当然更新数据的同时不妨碍开始其他任务，直接点击想开始的任务即可，不需要等待数据刷新完毕。

月月比功能正在开发中，但是需要等到月月比进口再次开放才可以测试。

**Comment by cool2008** [comment]
![3](https://user-images.githubusercontent.com/66152697/84363084-cdbe4e00-ac00-11ea-9cd7-e6406e4ac14e.PNG)
每次关闭后都显示

**Comment by ExcaliburEX** [comment]
> ![3](https://user-images.githubusercontent.com/66152697/84363084-cdbe4e00-ac00-11ea-9cd7-e6406e4ac14e.PNG)
> 每次关闭后都显示

按下面的`退出`按钮退出，直接叉掉会导致线程错误。

**Comment by cool2008** [comment]
大大，月月比开始测试了吗？时间只有两天

**Comment by ExcaliburEX** [comment]
> 大大，月月比开始测试了吗？时间只有两天

貌似月月比的题库，各个地方都不同，所以即使开发出来，意义也不大、:smile:

**Comment by ExcaliburEX** [comment]
> 大大，月月比开始测试了吗？时间只有两天

月月比已经实现。
