### ISSUE TITLE
登录机制似乎发生了变化？

### ISSUE THREAD

**Issue by miaoxw** [ExcaliburEX/AutomaticOnlineAnswer#7]
今天登录后发现自动学习时会有登录状态失效的问题。F12跟踪了一下，发现在获取验证码的POST请求中新增了一个名为`SESSION`的cookie，并且有效时长为会话长度。
试着将`log_driver`在后续自动化操作中复用，功能似乎都很正常，那么这里高度怀疑是网站的登录机制发生了变化。这里想请原作者确认一下是否是这里出了问题。
目前正在着手脚本的修改，如果同样的问题能被复现的话，那我随时准备PR就是啦~能够想到的问题是，这样的修改将导致三项学习进程不再能够多开，必须顺序进行了。

**Comment by ExcaliburEX** [comment]
> 今天登录后发现自动学习时会有登录状态失效的问题。F12跟踪了一下，发现在获取验证码的POST请求中新增了一个名为`SESSION`的cookie，并且有效时长为会话长度。 试着将`log_driver`在后续自动化操作中复用，功能似乎都很正常，那么这里高度怀疑是网站的登录机制发生了变化。这里想请原作者确认一下是否是这里出了问题。 目前正在着手脚本的修改，如果同样的问题能被复现的话，那我随时准备PR就是啦~能够想到的问题是，这样的修改将导致三项学习进程不再能够多开，必须顺序进行了。

最近收到了一些信息看起来是这样的，无奈最近工作繁忙:cry:，没有具体细看，如果你有空修改的话可以直接PR@miaoxw

**Comment by miaoxw** [comment]
好的了解
